### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by mbaechler** [zio/zio-crypto#15]
Looking at this project, it looks like there's no update for several months.
For such a young project, it sounds a lot like it has been abandoned.
Could you confirm the status of the project please?

**Comment by emarx** [comment]
Hi @mbaechler -- I wrote the initial code for this repo. There's an open PR here (https://github.com/zio/zio-crypto/pull/9) that once merged, I think will provide an interesting enough set of functionality. I had other work come up, but would love to get back in it a bit and see a release. I'll follow up on the PR there.

**Comment by emarx** [comment]
Merged!

**Comment by mbaechler** [comment]
I'll have a look, thank you for the feedback.
